# 書籍
books = BookGenre.create(name: "書籍")
books_1 = .children.create(name: "文学・小説")
books_2 = .children.create(name: "社会・ビジネス")
books_3 = .children.create(name: "旅行・地図")
books_4 = .children.create(name: "趣味")
books_5 = .children.create(name: "実用・教育")
books_6 = .children.create(name: "アート・教養・エンタメ")
books_7 = .children.create(name: "辞典・図鑑・語学・辞書")

# 雑誌
magazine = BookGenre.create(name: "雑誌")
magazine_1 = .children.create(name: "ファッション・美容誌")
magazine_2 = .children.create(name: "情報誌")
magazine_3 = .children.create(name: "男性コミック誌")
magazine_4 = .children.create(name: "女性コミック誌")
magazine_5 = .children.create(name: "児童・学習誌")
magazine_6 = .children.create(name: "文芸・教育誌・その他")
magazine_7 = .children.create(name: "ウィークリーブック")

# 漫画
comic = BookGenre.create(name: "漫画")
comic_1 = .children.create(name: "少年漫画")
comic_2 = .children.create(name: "少女漫画")
comic_3 = .children.create(name: "青年漫画")
comic_4 = .children.create(name: "女性漫画")
comic_5 = .children.create(name: "TL漫画")
comic_6 = .children.create(name: "BL漫画")
comic_7 = .children.create(name: "大人向け漫画")
comic_8 = .children.create(name: "オリジナル・同人")

# ラノベ
lightnovel = BookGenre.create(name: "ライトノベル")
lightnovel_1 = .children.create(name: "ハイファンタジー")
lightnovel_2 = .children.create(name: "ローファンタジー")
lightnovel_3 = .children.create(name: "恋愛(異世界)")
lightnovel_4 = .children.create(name: "恋愛(現実世界)")
lightnovel_5 = .children.create(name: "文芸(純文学)")
lightnovel_6 = .children.create(name: "文芸(ヒューマドラマ)")
lightnovel_7 = .children.create(name: "文芸(歴史)")
lightnovel_8 = .children.create(name: "文芸(推理)")
lightnovel_9 = .children.create(name: "文芸(ホラー)")
lightnovel_10 = .children.create(name: "文芸(アクション)")
lightnovel_11 = .children.create(name: "文芸(コメディー)")
lightnovel_12 = .children.create(name: "SF(VRゲーム)")
lightnovel_13 = .children.create(name: "SF(宇宙)")
lightnovel_14 = .children.create(name: "SF(空想科学)")
lightnovel_15 = .children.create(name: "SF(パニック)")
lightnovel_16 = .children.create(name: "その他(童話)")
lightnovel_17 = .children.create(name: "その他(詩)")
lightnovel_18 = .children.create(name: "その他(エッセイ)")
lightnovel_19 = .children.create(name: "その他")
lightnovel_20 = .children.create(name: "異世界転生/転移(恋愛)")
lightnovel_21 = .children.create(name: "異世界転生/転移(ファンタジー)")
lightnovel_22 = .children.create(name: "異世界転生/転移(文芸・SF・その他)")

# 子供の本
childbook = BookGenre.create(name: "こどもの本")
childbook_1 = .children.create(name: "絵本")
childbook_2 = .children.create(name: "図鑑・辞典")
childbook_3 = .children.create(name: "学習まんが")
childbook_4 = .children.create(name: "攻略本")
childbook_5 = .children.create(name: "知育")
childbook_6 = .children.create(name: "小学館ジュニア文庫")

# 電子書籍・コンテンツ
ebook = BookGenre.create(name: "電子書籍・コンテンツ")
ebook_1 = .children.create(name: "コミック")
ebook_2 = .children.create(name: "書籍・ラノベ")
ebook_3 = .children.create(name: "雑誌")
ebook_4 = .children.create(name: "Webコンテンツ・アプリ")
ebook_5 = .children.create(name: "写真集")
